Application/UcuzSepet.Application.Admin/Controllers/SubCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using UcuzSepet.Application.Admin.Base;
using UcuzSepet.Business.Service.IServices;
using UcuzSepet.Data.Domain.Entities;
using UcuzSepet.Data.EF.Components;

namespace UcuzSepet.Application.Admin.Controllers {

    /// <summary>
    /// Sub Category Controller, Inherited from BaseController<SubCategory>
    /// </summary>
    public class SubCategoryController : BaseController<SubCategory> {

        public new ISubCategoryService Service { get; }
        public ICategoryService CategoryService { get; }

        public SubCategoryController(ISubCategoryService service, ILogger<SubCategory> logger, ICategoryService categoryService)
            : base(service, logger) {
            Service = service;
            CategoryService = categoryService;
        }


        /// <summary>
        /// Inser View. Override from Base Controller.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public override IActionResult Insert() {
            FillCategoriesIntoViewBag();
            return View();
        }

        /// <summary>
        /// Edit View, Get Sub Category and Return into the View. Override from Base Controller.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public override IActionResult Edit(int id) {
            FillCategoriesIntoViewBag();
            var result = Service.GetBy(x => x.Id == id);
            return View(result);
        }

        /// <summary>
        /// Index View. Override from Base Controller.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public override IActionResult Index() {
            var results = Service.GetSubCategoriesWithInclude();
            return View(results);
        }

        /// <summary>
        /// Insert View [HttpPost], Create new SubCategory. Override from Base Controller.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public override IActionResult Insert(SubCategory model) {
            if (ModelState.IsValid) {
                Service.Add(model);
                if (Service.Save()) {
                    return RedirectToAction("Index");
                }
            }
            else {
                FillCategoriesIntoViewBag();
            }
            return View();
        }

        /// <summary>
        /// Get All Categories from CategoryService and fill into ViewBag
        /// </summary>
        void FillCategoriesIntoViewBag() {
            var categories = CategoryService.GetAll();
            ViewBag.Categories = categories;
        }

    }
}

Application/UcuzSepet.Application.Admin/Views/SubCategory/Edit.cshtml
@model SubCategory


<form method="post">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input class="form-control" id="categoryName" placeholder="Sub Category name" asp-for="Name">
    </div>
    <div class="form-group">
        <label asp-for="RootCategory">Root Category</label>
        <select asp-for="RootCategoryId" name="RootCategoryId" 
                class="form-control"
                asp-items="@(new SelectList(ViewBag.Categories,"Id","Name"))">
            <option value="0">Select</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">
        Save
    </button>
</form>

Application/UcuzSepet.Application.Admin/Views/SubCategory/Index.cshtml
@model IEnumerable<SubCategory>

<partial name="_NewItemButtonPartial" />
<div class="table-responsive">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">RootCategory</th>
                <th scope="col">#</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var subCategory in Model) {
                <tr>
                    <th scope="row">@subCategory.Id</th>
                    <td>@subCategory.Name</td>
                    <td>@(subCategory.RootCategory != null ? subCategory.RootCategory.Name : string.Empty)</td>
                    <td><a asp-controller="SubCategory" asp-action="Edit" asp-route-id="@subCategory.Id">Edit</a></td>
                </tr>
            }
        </tbody>
    </table>
 </div>

Application/UcuzSepet.Application.Admin/Views/SubCategory/Insert.cshtml
@model SubCategory


<form method="post">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input class="form-control" id="categoryName" placeholder="Category name" asp-for="Name">
    </div>
    <div class="form-group">
        <label asp-for="RootCategory">Root Category</label>
        <select asp-for="RootCategory" name="RootCategoryId"
                class="form-control"
                asp-items="@(new SelectList(ViewBag.Categories,"Id","Name"))">
            <option value="0">Select</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">
        Save
    </button>
</form>