Application/UcuzSepet.Application.Admin/Models/BrandViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace UcuzSepet.Application.Admin.Models {

    /// <summary>
    /// Brand Entity View Model
    /// </summary>
    public class BrandViewModel {
        public int Id { get; set; }
        [Required]
        [MaxLength(50)]
        public string Name { get; set; }
    }
}

Application/UcuzSepet.Application.Admin/Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using UcuzSepet.Application.Admin.Base;
using UcuzSepet.Business.Service.IServices;
using UcuzSepet.Data.Domain.Entities;

namespace UcuzSepet.Application.Admin.Controllers {

    /// <summary>
    /// Brand Controller, Inherited from BaseController<Brand>
    /// </summary>
    public class BrandController : BaseController<Brand> {

        public new IBrandService Service { get; }

        public BrandController(IBrandService service, ILogger<Brand> logger)
            : base(service, logger) {
            Service = service;
        }

        /// <summary>
        /// Edit View, Get Brand by Id and Return into Edit View. Override from Base Controller.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public override IActionResult Edit(int id) {
            var result = Service.GetBy(x => x.Id == id);
            return View(result);
        }
    }
}

Application/UcuzSepet.Application.Admin/Views/Brand/Edit.cshtml
@model Brand


<form method="post">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input class="form-control" id="name" placeholder="Brand name" asp-for="Name" value="@Model.Name">
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
    <div>@ViewBag.ErrorMessage</div>
</form>

Application/UcuzSepet.Application.Admin/Views/Brand/Index.cshtml
@model IEnumerable<Brand>

<partial name="_NewItemButtonPartial" />

<div class="table-responsive">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">#</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var brand in Model) {

                <tr>
                    <th scope="row">@brand.Id</th>
                    <td>@brand.Name</td>
                    <td><a asp-controller="Brand" asp-action="Edit" asp-route-id="@brand.Id">Edit</a></td>
                </tr>
            }

        </tbody>
    </table>
</div>

Application/UcuzSepet.Application.Admin/Views/Brand/Insert.cshtml
@model Brand


<form method="post">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input class="form-control" id="name" placeholder="Brand name" asp-for="Name">
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
    <div>@ViewBag.ErrorMessage</div>
</form>