Application/UcuzSepet.Application.Admin/Models/CategoryViewModel.cs
using System.ComponentModel.DataAnnotations;
using UcuzSepet.Data.Domain.Entities;

namespace UcuzSepet.Application.Admin.Models {

    /// <summary>
    /// Category Entity View Model
    /// </summary>
    public class CategoryViewModel {
        public int Id { get; set; }

        [Required]
        [MaxLength(50)]
        public string Name { get; set; }
    }
}

Application/UcuzSepet.Application.Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using UcuzSepet.Application.Admin.Base;
using UcuzSepet.Business.Service.IServices;
using UcuzSepet.Data.Domain.Entities;


namespace UcuzSepet.Application.Admin.Controllers {
    /// <summary>
    /// Category Controller, Inherited from BaseController<Category>
    /// </summary>
    public class CategoryController : BaseController<Category> {

        public new ICategoryService Service { get; }

        public CategoryController(ICategoryService service, ILogger<Category> logger)
            : base(service, logger) {
            Service = service;
        }

        /// <summary>
        /// Edit View, Get Category by Id and Return into Edit View. Override from Base Controller.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public override IActionResult Edit(int id) {
            var result = Service.GetBy(x => x.Id == id);
            return View(result);
        }

    }
}

Application/UcuzSepet.Application.Admin/Views/Category/Edit.cshtml
@model Category


<form method="post">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input class="form-control" id="name" placeholder="Brand name" asp-for="Name" value="@Model.Name">
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
    <div>@ViewBag.ErrorMessage</div>
</form>

Application/UcuzSepet.Application.Admin/Views/Category/Index.cshtml
@model IEnumerable<Category>

<partial name="_NewItemButtonPartial" />
<div class="table-responsive">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">#</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var category in Model) {

                <tr>
                    <th scope="row">@category.Id</th>
                    <td>@category.Name</td>
                    <td><a asp-controller="Category" asp-action="Edit" asp-route-id="@category.Id">Edit</a></td>
                </tr>
            }

        </tbody>
    </table>
</div>

Application/UcuzSepet.Application.Admin/Views/Category/Insert.cshtml
@model Category
@{
}


<form method="post">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input class="form-control" id="categoryName" placeholder="Category name" asp-for="Name">
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
    <div>@ViewBag.MailResultMessage</div>
</form>