Application/UcuzSepet.Application.Admin/Models/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using UcuzSepet.Data.Domain.Entities;

namespace UcuzSepet.Application.Admin.Models {

    /// <summary>
    /// Product Entity View Model
    /// </summary>
    public class ProductViewModel {
        public int Id { get; set; }
        [Required]
        [MaxLength(50)]
        public string Name { get; set; }
        [Required]
        public int SubCategoryId { get; set; }
        [Required]
        public int BrandId { get; set; }
        [Required]
        public decimal Price { get; set; }
        public string Properties { get; set; }

        public SubCategory SubCategory { get; set; }
        public Brand Brand { get; set; }

        public IEnumerable<Category> Categories { get; set; }
        public IEnumerable<SubCategory> SubCategories { get; set; }
        public IEnumerable<Brand> Brands { get; set; }

    }
}

Application/UcuzSepet.Application.Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using UcuzSepet.Application.Admin.Base;
using UcuzSepet.Application.Admin.Models;
using UcuzSepet.Business.Service.IServices;
using UcuzSepet.Business.Service.Services;
using UcuzSepet.Data.Domain.Entities;
using UcuzSepet.Data.EF.Components;


namespace UcuzSepet.Application.Admin.Controllers {
    /// <summary>
    /// Product Controller, Inherited from BaseController<Product>
    /// </summary>
    public class ProductController : BaseController<Product> {
        public new IProductService Service { get; }
        public ICategoryService CategoryService { get; }
        public ISubCategoryService SubCategoryService { get; }
        public IBrandService BrandService { get; }

        public ProductController(IProductService service, ILogger<Product> logger, ICategoryService categoryService, ISubCategoryService subCategoryService, IBrandService brandService)
         : base(service, logger) {
            Service = service;
            CategoryService = categoryService;
            SubCategoryService = subCategoryService;
            BrandService = brandService;
        }

        /// <summary>
        /// Index View, Get All Products with related entities and Return into Index View. Override from Base Controller.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public override IActionResult Index() {
            var results = Service.GetAllProductsWithInclude();
            return View(results);
        }

        /// <summary>
        /// Edit View, Get Product by Id with related entities and Return into Edit View. Override from Base Controller.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public override IActionResult Edit(int id) {

            try {

                var model = Service.GetByIdWithInclude(id);
                var categories = CategoryService.GetAll().ToList();
                ViewBag.Categories = categories;

                var subCategories = SubCategoryService.GetSubCategoriesByRootCategoryId(model.SubCategory.RootCategoryId);
                ViewBag.SubCategories = subCategories;

                var brands = BrandService.GetAll().ToList();
                ViewBag.Brands = brands;

                return View(model);
            }
            catch (Exception ex) {
                Logger.LogError($"Error occured at ProductController at [HttpGet] Edit(int id) method with parameter: {id} --> {ex}");
            }
            return View();
        }

        /// <summary>
        /// Insert View, Get related entities and Return into Insert View. Override from Base Controller.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public override IActionResult Insert() {

            try {
                var categories = CategoryService.GetAll().ToList();
                ViewBag.Categories = categories;

                var brands = BrandService.GetAll().ToList();
                ViewBag.Brands = brands;

                return View();
            }
            catch (Exception ex) {
                Logger.LogError($"Error occured at ProductController at [HttpGet] Insert() method --> {ex}");
            }
            return View();
        }

        /// <summary>
        /// Get Sub Categories By Root Category Id
        /// </summary>
        /// <param name="categoryId"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult GetSubCategories(int categoryId) {
            var subCategories = SubCategoryService.GetSubCategoriesByRootCategoryId(categoryId);
            return Json(new SelectList(subCategories, "Id", "Name"));
        }

        /// <summary>
        /// Edit View [HttpPost], Update Product. Override from Base Controller.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public override IActionResult Edit(Product model) {
            throw new NotImplementedException();
        }
    }
}

Application/UcuzSepet.Application.Admin/Views/Product/Edit.cshtml
@model Product

<script src="~/lib/jquery/dist/jquery.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#Category").change(function () {
            var url = '@Url.Content("~/")' + "Product/GetSubCategories";
            var source = "#Category";
            $.getJSON(url, { categoryId: $(source).val() },
                function (data) {
                    var items = '';
                    $("#SubCategory").empty();
                    items += "<option value='0'>Select</option>";
                    $.each(data, function (i,subCategory) {
                        items += "<option value='"+subCategory.value+"'>"+subCategory.text+"</option>";
                    });
                    $("#SubCategory").html(items);
                });

        });

    });
</script>

<form method="post">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label for="Category">Category</label>
        <select asp-for="SubCategory.RootCategoryId" id="Category"
                class="form-control"
                asp-items="@(new SelectList(ViewBag.Categories,"Id","Name"))">
            <option value="0">Select</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="SubCategoryId">Sub Category</label>
        <select asp-for="SubCategoryId" id="SubCategory" name="SubCategoryId"
                asp-items="@(new SelectList(ViewBag.SubCategories,"Id","Name"))"
                class="form-control">
            <option value="0">Select</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="BrandId">Brand</label>
        <select asp-for="BrandId" name="BrandId"
                class="form-control"
                asp-items="@(new SelectList(ViewBag.Brands,"Id","Name"))">
            <option value="0">Select</option>
        </select>
    </div>
    <div class=" form-group">
        <label asp-for="Name">Name</label>
        <input class="form-control" id="name" placeholder="Product name" asp-for="Name" value="@Model.Name">
    </div>
    <div class="form-group">
        <label asp-for="Price">Price</label>
        <input class="form-control" id="name" placeholder="Price" asp-for="Price" value="@Model.Price">
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

Application/UcuzSepet.Application.Admin/Views/Product/Index.cshtml
@model IEnumerable<Product>

<partial name="_NewItemButtonPartial" />

<div class="table-responsive">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Category</th>
                <th scope="col">Brand</th>
                <th scope="col">Name</th>
                <th scope="col">Price</th>
                <th scope="col">#</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model) {

                <tr>
                    <th scope="row">@product.Id</th>
                    <td>@product.SubCategory.Name</td>
                    <td>@product.Brand.Name</td>
                    <td>@product.Name</td>
                    <td>@product.Price</td>
                    <td><a asp-controller="Product" asp-action="Edit" asp-route-id="@product.Id">Edit</a></td>
                </tr>
            }

        </tbody>
    </table>
</div>

Application/UcuzSepet.Application.Admin/Views/Product/Insert.cshtml
@model Product

<script src="~/lib/jquery/dist/jquery.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#Category").change(function () {
            var url = '@Url.Content("~/")' + "Product/GetSubCategories";
            var source = "#Category";
            $.getJSON(url, { categoryId: $(source).val() },
                function (data) {
                    var items = '';
                    $("#SubCategory").empty();
                    items += "<option value='0'>Select</option>";
                    $.each(data, function (i,subCategory) {
                        items += "<option value='"+subCategory.value+"'>"+subCategory.text+"</option>";
                    });
                    $("#SubCategory").html(items);
                });

        });

    });
</script>

<form method="post">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label for="Category">Category</label>
        <select for="Category" id="Category"
                class="form-control"
                asp-items="@(new SelectList(ViewBag.Categories,"Id","Name"))">
            <option value="0">Select</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="SubCategoryId">Sub Category</label>
        <select asp-for="SubCategoryId" id="SubCategory" name="SubCategoryId"
                class="form-control">
            <option value="0">Select</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="BrandId">Brand</label>
        <select asp-for="BrandId" name="BrandId"
                class="form-control"
                asp-items="@(new SelectList(ViewBag.Brands,"Id","Name"))">
            <option value="0">Select</option>
        </select>
    </div>
    <div class=" form-group">
        <label asp-for="Name">Name</label>
        <input class="form-control" id="name" placeholder="Product name" asp-for="Name" >
    </div>
    <div class="form-group">
        <label asp-for="Price">Price</label>
        <input class="form-control" id="name" placeholder="Price" asp-for="Price" >
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>